(()=>{
// Replace these two public project values after creating a Supabase Free project.
// Use the publishable/anon key only; never put a service-role or secret key here.
const SUPABASE_URL='https://ptnlkrxnvpqgowgtibee.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_DEAsIf_9RfF4kHa8hrip3g_3jAkfRCh';
const STORE_KEY='kintai-note-v1',RATES_KEY='kintai-note-rates-v1',NAME_KEY='kintai-name';
const LAST_KEY='kintai-cloud-last-payload-v1',BACKUP_PREFIX='kintai-cloud-backup-v1-';
const $=id=>document.getElementById(id),status=$('cloudStatus'),message=$('cloudMessage');
const rawSet=Storage.prototype.setItem,rawGet=Storage.prototype.getItem;
let client=null,user=null,channel=null,applying=false,pushTimer=null,pulling=false;
const say=(text,isError=false)=>{message.textContent=text;message.style.color=isError?'#b34343':'#526477'};
function readPayload(){let parse=(s,f)=>{try{return JSON.parse(s||'')}catch{return f}};return {records:parse(rawGet.call(localStorage,STORE_KEY),'{}'),rates:parse(rawGet.call(localStorage,RATES_KEY),'{}'),name:rawGet.call(localStorage,NAME_KEY)||''}}
function stableValue(v){if(Array.isArray(v))return v.map(stableValue);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stableValue(v[k])]));return v}
function payloadText(p){return JSON.stringify(stableValue({records:p.records||{},rates:p.rates||{},name:p.name||''}))}
function hasData(p){return Object.keys(p.records||{}).length>0||Object.keys(p.rates||{}).length>0||!!p.name}
function keepLocalBackup(){const p=readPayload();rawSet.call(localStorage,BACKUP_PREFIX+new Date().toISOString(),payloadText(p));return p}
function writePayload(p){applying=true;try{rawSet.call(localStorage,STORE_KEY,JSON.stringify(p.records||{}));rawSet.call(localStorage,RATES_KEY,JSON.stringify(p.rates||{}));rawSet.call(localStorage,NAME_KEY,p.name||'')}finally{applying=false}}
function setLast(p){rawSet.call(localStorage,LAST_KEY,payloadText(p))}
function paint(){location.reload()}
function askSyncChoice(){const box=$('syncPrompt');return new Promise(resolve=>{const finish=useLocal=>{box.hidden=true;resolve(useLocal)};$('syncUseLocal').onclick=()=>finish(true);$('syncUseCloud').onclick=()=>finish(false);box.hidden=false})}
async function push(){if(!client||!user||applying||pulling)return;const p=readPayload();try{status.textContent='クラウドへ保存中…';const {error}=await client.from('kintai_shared_state').upsert({user_id:user.id,payload:p,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;setLast(p);status.textContent='クラウドに同期済み';say('この端末の変更をクラウドへ保存しました。')}catch(e){status.textContent='同期できません';say('クラウドへの保存に失敗しました：'+(e.message||e),true)}}
function schedulePush(){if(!user||applying)return;clearTimeout(pushTimer);pushTimer=setTimeout(push,700)}
Storage.prototype.setItem=function(k,v){rawSet.call(this,k,v);if(this===localStorage&&[STORE_KEY,RATES_KEY,NAME_KEY].includes(String(k)))schedulePush()};
async function syncRealtime(){if(!client||!user)return;channel=client.channel('kintai-shared-state').on('postgres_changes',{event:'*',schema:'public',table:'kintai_shared_state',filter:'user_id=eq.'+user.id},async e=>{const p=e.new?.payload;if(!p)return;const now=readPayload(),incoming=payloadText(p);if(incoming===payloadText(now))return;clearTimeout(pushTimer);const previous=rawGet.call(localStorage,LAST_KEY);if(payloadText(now)!==previous){const takeCloud=confirm('別の端末で勤怠データが更新されました。\nOK：クラウド側の記録をこの端末に読み込む\nキャンセル：この端末の記録を残し、クラウドへ保存する');if(!takeCloud){schedulePush();return}}keepLocalBackup();writePayload(p);setLast(p);say('別の端末の更新を読み込みました。');paint()}).subscribe()}
async function connected(session){user=session.user;status.textContent='アカウント確認中…';$('cloudLogin').hidden=true;$('cloudSignup').hidden=true;$('cloudLogout').hidden=false;const {data,error}=await client.from('kintai_shared_state').select('payload,updated_at').eq('user_id',user.id).maybeSingle();if(error){status.textContent='クラウド接続エラー';say('Supabaseのテーブル/RLS設定を確認してください：'+error.message,true);return}const local=readPayload(),last=rawGet.call(localStorage,LAST_KEY);if(!data){status.textContent='クラウドへ初回保存中…';await push();await syncRealtime();return}const cloud=data.payload||{records:{},rates:{},name:''};if(hasData(local)&&payloadText(local)!==last){keepLocalBackup();const merge=await askSyncChoice();if(merge){const merged={records:{...(cloud.records||{}),...(local.records||{})},rates:{...(cloud.rates||{}),...(local.rates||{})},name:local.name||cloud.name||''};writePayload(merged);setLast(local);await push();status.textContent='クラウドに同期済み';await syncRealtime();paint();return}}const changed=payloadText(cloud)!==payloadText(local);writePayload(cloud);setLast(cloud);status.textContent='クラウドに同期済み';say('ログイン中です。PCとスマホでこのアカウントの記録を共有します。');await syncRealtime();if(changed)paint()}
async function login(signup){if(!client){say('Supabase接続設定が未完了です。設定ガイドの手順が必要です。',true);return}const email=$('cloudEmail').value.trim(),password=$('cloudPassword').value;if(!email||!password){say('メールアドレスとパスワードを入力してください。',true);return}say(signup?'アカウントを登録しています…':'ログインしています…');const res=signup?await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}):await client.auth.signInWithPassword({email,password});if(res.error){say(res.error.message,true);return}if(signup&&!res.data.session){say('確認メールを送りました。メール内の確認リンクを開いてからログインしてください。');return}if(res.data.session)await connected(res.data.session);else say('登録できました。ログインしてください。')}
async function boot(){if(!window.supabase||SUPABASE_URL.startsWith('PASTE_')||SUPABASE_ANON_KEY.startsWith('PASTE_')){status.textContent='Supabaseの初期設定が必要です';say('共有を有効にするには、初期設定ガイドに沿って無料プロジェクトを作成し、URLと公開キーを設定します。');$('cloudLogin').disabled=true;$('cloudSignup').disabled=true;return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);$('cloudLogin').onclick=()=>login(false);$('cloudSignup').onclick=()=>login(true);$('cloudLogout').onclick=async()=>{await client.auth.signOut();user=null;if(channel)client.removeChannel(channel);channel=null;status.textContent='ログアウトしました';$('cloudLogin').hidden=false;$('cloudSignup').hidden=false;$('cloudLogout').hidden=true;say('端末内データはこのブラウザーに残っています。')};const {data,error}=await client.auth.getSession();if(error){say(error.message,true);return}if(data.session)await connected(data.session);else{status.textContent='未ログイン';say('登録済みの方はログインしてください。初めての方は「初めての登録」を押します。')}}
boot();
})();
